accessibilityJob: false
alwaysRunPostSteps: false
appium: null
autosplit: true
betaFeature:
    setPartiallyCompletedAsCompleted: false
cacheDirectories:
    - CacheDir
cacheKey: '{{ checksum "requirements.txt" }}'
captureScreenRecordingForScenarios: false
codeDirectory: myhyper-execute-demo
collectLocalGitData: true
combineTasksInMatrixMode: false
cypress: false
differentialUpload:
    enabled: false
    forcedDisabled: false
    ttlHours: null
dynamicAllocation: false
errorCategorizedOnFailureOnly: false
framework:
    additional_args: null
    args:
        appId: ""
        appPath: ""
        artifacts: false
        avoidAppLaunch: false
        deviceSelectionStrategy: ""
        devices: []
        disableReleaseDevice: false
        filters:
            attributes: []
        fixedIP: ""
        isRealMobile: null
        isVirtualDevice: false
        language: ""
        locale: ""
        minorOsVersion: false
        mitmProxy: false
        mobileDC: null
        networkHar: false
        otherApps: []
        platformName: ""
        playwrightRD: false
        preservedDevice: false
        queueTimeout: 0
        resignApp: true
        shards:
            mappings: []
        skipInstall: false
        skipUninstallPreviousBuild: false
        skipXMLOnRun: false
        testSuiteAppId: ""
        testSuitePath: ""
        uninstallPreviousBuild: false
        xcTestPlanId: ""
        xcTestPlanPath: ""
    baseCommand: ""
    defaultReports: false
    discoveryFlags: []
    discoveryMode: ""
    discoveryType: ""
    downloadURL: ""
    flags: []
    isTestNGXMLSuite: false
    licenseKey: ""
    name: ""
    runnerFlags: []
    toscaArgs: null
    userdefinediscovery: false
    version: ""
    workingDirectory: ""
globalPost:
    commands: []
    completed: false
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
globalPre:
    cache: false
    commands: []
    completed: false
    maxRetries: 0
    mode: ""
    runson: ""
    shell: ""
    workingDirectory: ""
globalTimeout: 90
jobID: e5fd3346-c11c-4cce-b247-78d0f31f6976
jobLabel:
    - selenium-pyunit
    - autosplit
key: LT_vNlHDWl1n7Rb5PJQJXPmCXJltrBUQJaMpjH3v1L2XFNHBY4
linuxParallelism: 4
linuxTestRunnerCommand: python3 $test
localHTTPProxy: ""
matrix:
    browser:
        - chrome
        - firefox
    os:
        - win
        - linux
maxRetries: 1
maxRetriesPreSteps: 0
mergeArtifacts: true
meta: {}
parallelism: 4
partialReports:
    type: json
    location: /
    frameworkName: extent
    email:
        to: []
        metaInfo: []
        linkValidity: 0
    configPath: ""
    configPathURL: ""
platformConfig: null
post:
    - cat yaml/win/pyunit_hyperexecute_autosplit_sample.yaml
postDirectives:
    commands:
        - cat yaml/win/pyunit_hyperexecute_autosplit_sample.yaml
    shell: ""
    workingDirectory: ""
pre:
    - pip3 install -r requirements.txt --cache-dir CacheDir
preDirectives:
    commands:
        - pip3 install -r requirements.txt --cache-dir CacheDir
    maxRetries: 0
    shell: ""
    workingDirectory: ""
project:
    id: ""
    name: ""
    type: default
projectpath: ""
regionConfig:
    storage:
        enabled: false
        name: ""
        platform: azure
        region: ""
    vm: []
report: true
retryOnFailure: true
runson: ${matrix.os}
slackChannel: ""
sourcePayload:
    verifySSL: true
storageType: ""
testDiscovery:
    autosubset: true
    command: grep -nri 'HyperTestPyUnit' tests -ir --include=\*.py | sed 's/:.*//'
    linuxCommand: grep -nri 'HyperTestPyUnit' tests -ir --include=\*.py | sed 's/:.*//'
    mode: dynamic
    type: raw
    winCommand: grep -nri 'HyperTestPyUnit' tests -ir --include=\*.py | sed 's/:.*//'
testDiscoveryResultV3: []
testRunnerCommand: python3 $test
testSuiteStep: 90
testSuiteTimeout: 90
testSuites: []
triggerMode: false
tunnelOpts:
    testsPerTunnel: 10
unzipPayload: false
uploadArtefacts:
    - email:
        linkValidity: 0
        metaInfo: []
        to: []
      name: TestReport
      path:
        - example_report/**/*
user: rohanreddy
version: "0.1"
waitForArtefactsUpload: false
whiteLabelProductTag: ""
winParallelism: 4
winTestRunnerCommand: python3 $test
